### ISSUE TITLE
adapter board slim design

### ISSUE THREAD

**Issue by docop** [inaxeon/t9120riser#1]
Hi  So your design is very very great and quite usefull to understand the bifurcation and the trace design. Thanks for that. Also, i did see that you may have done a slim adapter for network card, using oculink connector. I try to figure out how to properly power the card and around a 8643 connector.. Do you think you can also share your schematic for that small one ?

Thanks in advance, very appreciated.

**Comment by inaxeon** [comment]
https://github.com/inaxeon/ocu2pciex8

**Comment by docop** [comment]
Oh Thanks a lot, very great! You got a nice find about your dc converter ADP2387 !  I will now try out to adapt for the 8643 or even 8654 connector.  Also, just to know, did you make this slimline to adapt to your riser like with a M.2 to oculink adapter card ?

**Comment by inaxeon** [comment]
There are thousands of possible DC-DC converters. That is just the one I happened to select. Does the job.

The OCu adapter isn't designed with any particular form factor in mind. "Small as possible" was the goal. It is presently used to add 10GbE to an ITX board with a non-OCuLink motherboard using an M.2 -> OCuLink adapter on the motherboard.

**Comment by docop** [comment]
Ohh ok so basically the m.2 data lane are extend via the oculink and the 'slimline adapter" transform the oculink to pci, at 85ohms and power is directly provided to the slot onboard, transparent from the m.2 . If i understand properly ?

**Comment by inaxeon** [comment]
The power for the peripheral plugged into my board all comes from the two pin Mini-Fit Jr connector on it. It does not draw anything from the OCuLink. There is no transformation going on OCuLink is PCIe.
